# -*- coding: utf-8 -*-
"""연습05_답안.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNpoGRHM698YB5P9P35sKJGgpSYExe0V

# 5.8 연습문제
"""

# 문제2
import pandas as pd
filename='/content/drive/MyDrive/data/covid.csv'
df=pd.read_csv(filename,encoding='cp949')
df
#1.항목열을 인덱스열로 지정한 후 ‘스마트폰’의 해당하는 모든 컬럼의 정보를 출력해보자.
df=pd.read_csv(filename,index_col=0,encoding='cp949')
df
#2.사례수가 가장 높은 항목의 모든 정보를 출력해보자.
result=df[df['사례수']==df['사례수'].max()]
result
#3.증가율이 높은 3개의 항목을 출력해보자.
newdata=df.sort_values('증가',ascending=False)
newdata.head(3)

from google.colab import drive
drive.mount('/content/drive')

#문제3-1
import pandas as pd
import matplotlib.pyplot as plt

filename='/content/drive/MyDrive/data/vaccine.csv'
vaccine=pd.read_csv(filename,encoding='cp949')
vaccine

# 문제3-2

import pandas as pd
import matplotlib.pyplot as plt

filename='/content/drive/MyDrive/data/vaccine.csv'
vaccine=pd.read_csv(filename,encoding='cp949')
# 필요없는 열을 삭제한다.
vaccine.drop(['day1sum','day1rate','day2sum','day2rate'], axis=1,inplace=True)
vaccine


# 새로운 열 생성
#vaccine['month']=pd.DatetimeIndex(vaccine['date']).month
#vaccine
# # 월별 평균 출력
#means=vaccine.groupby('month').mean()
#means
#1차 평균 접종수의 월별 그래프
#means['day1num'].plot(kind='bar')
#plt.show()

#문제3-3
vaccine.describe()

#문제3-4
# 새로운 열 생성
vaccine['month']=pd.DatetimeIndex(vaccine['date']).month
result=vaccine[['day1num','day2num','month']]
result.groupby('month').mean()

import pandas as pd
filename1='/content/drive/MyDrive/signup.csv'
filename2='/content/drive/MyDrive/professor.csv'
df1=pd.read_csv(filename1,encoding='cp949')
df2=pd.read_csv(filename2,encoding='cp949')
df1
#df2

df=pd.merge(df1,df2,on='담당교수')
df

df2.groupby(['학과']).count()