# -*- coding: utf-8 -*-
"""연습07_답안.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aABxqJmyudamCuWXMav6TIvv8qoUKymU

# 7장 시각화 라이브러리

## 7.4 시각화 라이브러리 연습 문제

###문제1 - 데이터 시각화의 필요성에 대하여 작성하시오.

#####기술적인 데이터 분석도 중요하지만 분석 결과 기반의 가치 창출이 데이터 분석의 핵심이다. 가치 창출을 위해서는 데이터 시각화를 적극적으로 활용하면 된다. 데이터 분석 역량은 데이터 수집, 가공, 분석 기법을 활용한 데이터 분석 기술이 필요하다. 반면 데이터 시각화에는 데이터 분석 결과를 시각적으로 표현해서 스토리텔링 하는 역량이다. 최근에는 데이터 시각화 활용이 쉬워지면서 고도의 전문 역량이 없더라도 데이터를 활용하여 인사이트를 발견하고, 스토리텔링을 할 수 있게 되었다. 이러한 데이터 시각화의 장점은 다음과 같다.

- 많은 양의 데이터를 시각적으로 요약
- 시각을 통한 데이터 인사이트 도출
- 3) 더 정확한 데이터 분석 결과 도출

###문제2 - 시각화 라이브러리 종류를 나열하고 차이점을 작성하시오.

- 맷플롯립(Matplotlib) : 파이썬에서 가장 많이 사용하며, 데이터를 차트나 플롯으로 시각화하는 라이브러리이다. 판다스의 데이터프레임을 바로 시각화 할 때도 내부적으로 맷플롯립을 사용한다. 맷플롯립은 데이터 분석 이전의 데이터 이해를 위한 시각화 또는 데이터 분석 이후의 결과를 시각화하기 위해 사용된다.
- 시본(Seaborn) : 맷플롯립을 기반으로 색 테마, 차트 기능 등을 추가해 주는 라이브러리이다. 맷플롯립과 함께 사용하며 히트맵, 카운트플롯 등을 제공한다.
- 폴리움(Folium) : 지도 데이터를 이용하여 위치 정보를 시각화하는 라이브러리이다. 자바스크립트 기반으로 상호작용의 그래프를 그릴 수 있다.
- 파이차트(Pyecharts) : 바이두(Baidu)에서 데이터 시각화를 위해 만든 파이썬 버전의 라이브러리이다. 다양한 그래프들이 내장되어 있고 자바스크립트 기반으로 상호작용의 그래프를 그릴 수 있다.
- 플로트나인(Plotnine) : R의 ggplot2에 기반을 두어 그래프를 그려주는 라이브러리이다. R 시각화 경힘이 있다면 편리하게 사용할 수 있다.
- 플로틀리(Plotly) : 상호작용의 그래프를 그려주는 라이브러리이다. R, 스칼라, 파이썬, 자바스크립트, 매트랩 등에서 사용할 수 있다. 사용이 쉽고 세련된 도구이며 온라인과 오프라인 버전이 따로 존재한다.
- 보케(Bekeh) : 맷플롯립의 대화형 버전으로, 다양한 기능을 제공하고 디자인이 훌륭하며 플롯(축)들 간의 링크가 가능하다. 반면 시본에 비교하여 문법이 복잡하다는 단점이 있다.

###문제3 - 시각화하는 과정을 단계별로 작성하시오.

#####판다스의 시리즈와 데이터프레임에는 plot() 이라는 시각화 함수를 내장하고 있다. plot() 함수도 맷플롯립을 임포트(import)하여 사용해야 한다. 일반적인 시각화 단계를 정리하면 다음과 같다.

- 1단계: 시각화 라이브러리 불러오기
- 2단계: x축, y축에 표시할 데이터 정하기
- 3단계: plot() 함수에 데이터 입력하기
- 4단계: 그래프 보여주기

###문제4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_excel('health_screenings_2020_1000ea.xlsx')
data3 = data.loc[:,['city_code','gender','waist']]

male_data = data3[data3['gender']==1].groupby('city_code')['waist'].mean()
female_data = data3[data3['gender']==2].groupby('city_code')['waist'].mean()

plt.figure(figsize=(12, 4))

plt.plot(male_data, 'bo--', label='Male')
plt.plot(female_data, 'ro--', label='Female')

plt.xlabel('Count')
plt.ylabel('Waist')
plt.title('2020 Health Screenings Waist')
plt.legend()
plt.grid()
plt.show()

"""###문제5"""

waistData = data3.loc[100:110,['waist']]

plt.figure(figsize=(10, 5))

plt.bar(waistData.index, waistData['waist'], color='c')

plt.ylim(50, 110)
plt.xlabel('Count')
plt.ylabel('Waist')
plt.title('2020 Health Screenings Waist')
plt.grid()
plt.show()

"""###문제6"""

lEyeData = data['eye_left']
rEyeData = data['eye_right']

plt.figure(figsize=(5, 5))

plt.scatter(lEyeData, rEyeData)

plt.xlim(0, 2.5)
plt.ylim(0, 2.5)
plt.xlabel('Eye Left')
plt.ylabel('Eye Right')
plt.title('2020 Health Screenings Scatter Graph')
plt.show()

"""###문제7"""

male_data = data3.loc[data3.gender==1, ['gender', 'waist']]
female_data = data3.loc[data3.gender==2, ['gender', 'waist']]

plt.figure(figsize=(10, 6))

plt.hist(male_data['waist'], bins=8, alpha = 0.5, label='Male')
plt.hist(female_data['waist'], bins=8, alpha = 0.5, label='Female')

plt.xlim(50, 115)
plt.xlabel('Waist')
plt.ylabel('Frequency')
plt.legend()
plt.grid()
plt.show()

"""###문제8"""

male = np.array(male_data['waist'], dtype=object)
female = np.array(male_data['waist'])

plt.figure(figsize=(10,5))

plt.boxplot([male,female], labels=['Male','Female'])

plt.xlabel('Gender')
plt.ylabel('Waist')
plt.title('2020 Health Screenings Male & Female Waist Box Plot')
plt.show()

"""###문제9"""

data6 = data.loc[:,['gender', 'height', 'weight', 'waist', 'drinking', 'smoking']]

data6.loc[data6['gender']==1,['gender']]='Male'
data6.loc[data6['gender']==2,['gender']]='Female'
data6.loc[(data6['smoking']==1) | (data6['smoking']==2),['smoking']]='Non-smoking'
data6.loc[data6['smoking']==3,['smoking']]='Smoking'

smoking = data6.groupby(['gender','smoking'])['smoking'].count()
smoking = smoking.to_frame(name='count')
smoking = smoking.reset_index()

plt.figure(figsize=(10,6))

sns.countplot(data=data6, x='smoking', hue='gender', order=['Smoking','Non-smoking'])

plt.title('Smoking Count Plot Graph')
plt.show()

"""###문제10"""

plt.figure(figsize=(10,6))

sns.violinplot(data=data6, x='gender', y='weight', hue='smoking')

plt.title('Violin Plot Graph')
plt.show()

"""###문제11"""

data6 = data.loc[:,['gender', 'height', 'weight', 'waist', 'drinking', 'smoking']]

plt.figure(figsize=(10,6))

correlation_data6 = data6.corr()
upp_mat = np.triu(correlation_data6)

sns.heatmap(correlation_data6, annot=True, cmap='YlGnBu', mask=upp_mat)

plt.title('Heat Map Graph')
plt.show()