# -*- coding: utf-8 -*-
"""예제05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDZrg1xKNFNJofutaok4SHllkZI-4s5B

# 5.2 판다스 객체 생성
"""

from google.colab import drive
drive.mount('/content/drive')

"""## (1) Series와 DataFrame

"""

# 정수형
import pandas as pd
s= pd.Series([95, 90, 85, 90, 95])
s

# 실수형
s = pd.Series([4, 3.5, 3.8, 3, 3.7])
s

# 인덱스지정하기
s=pd.Series([90,80,95],index=['A','B','C'])
s

# 넘파이로 배열생성하기
import numpy as np
import pandas as pd
arr = np.arange(12).reshape(4,3)
print(arr)
print()
df = pd.DataFrame(arr)
print(df)

# 딕셔너리로 배열생성하기
df = pd.DataFrame({'name':['장은실','오경선','양숙희'],
                    'score':[90,80,95],
                    'dept':['com','eng','math']})
df

#csv파일 불러오기
filename='/content/drive/MyDrive/mobile.csv'
df = pd.read_csv(filename)
df

#filename='/content/drive/MyDrive/mobile.csv'
df = pd.read_csv(filename, index_col=0)
df

"""# 5.3 판다스 데이터 확인하기"""

filename='/content/drive/MyDrive/weather.csv'
df = pd.read_csv(filename)
df

df.shape

df.head()

df.tail(3)

df.index

df.columns

df.describe()

#기온(temp) 컬럼의 평균 출력하기
df['temp'].mean()

df.sort_values(by='max_wind')

df.sort_values(by='max_wind', ascending=False)

import pandas as pd
filename='/content/drive/MyDrive/bank.csv'
bank=pd.read_csv(filename)
bank['job'].value_counts()
bank['job'].value_counts(ascending=True)

bank['job'].unique()

"""# 5.4 판다스 데이터 선택하기

## 열 선택하기
"""

df['temp'] # df.temp
type(df['temp'])

df[['date','temp']]

df.loc[:,['date','temp']]

df.iloc[:,[0,1]]

"""## 행 선택하기"""

df[0:3]

df.index=df['date']
df.loc['2010-08-01',['temp','mean_wind']]

df.iloc[3]

df.iloc[1:3,0:2]

"""## 불인덱싱"""

w=df['temp']>=30
df[w]

w=(df['temp']>=30) & (df['max_wind']>=9)
df[w]

w=df['temp']==df['temp'].max()
df[w]

"""# 5.5 판다스 결측 데이터 처리하기"""

df[df['max_wind'].isna()]

# 결측데이터 컬럼별 확인
df.isnull().sum()

df2=df.dropna()
df2.isnull().sum()

# 결측 데이터 대체
df['max_wind'].fillna(df['max_wind'].mean(),inplace=True)
df['mean_wind'].fillna(df['mean_wind'].mean(),inplace=True)

# 결측 데이터 대체
# df.fillna(df.mean(),inplace=True) 오류 발생

df.isnull().sum()

"""# 5.6 판다스 데이터 가공하기"""

filename='/content/drive/MyDrive/dust1.xlsx'
dust=pd.read_excel(filename)
dust.head()

# 컬럼(변수) 삭제하기
dust=dust.drop(['지역','망','측정소코드'], axis=1)

dust.head()

# 컬럼생성하기
dust['city']='서울'

dust.head()

dust.rename(columns={'측정소명':'name',
                     '측정일시':'date',
                     '주소':'addr'}, inplace=True)

dust.columns

dust.dtypes

# 숫자 int형을 문자열형으로 변환
dust['date']=dust['date'].astype(str)
dust['date']=dust['date'].str.slice(0,8)
dust.dtypes

dust['date']=pd.to_datetime(dust['date'])
dust.dtypes

dust['year']=dust['date'].dt.year
dust['month']=dust['date'].dt.month
dust['day']=dust['date'].dt.day
dust.head()

filename='/content/drive/MyDrive/nation.xlsx'
s1=pd.read_excel(filename)
s1

filename='/content/drive/MyDrive/code.xlsx'
s2=pd.read_excel(filename)
s2

pd.merge(s1,s2,on='국적코드')

# 오른쪽 컬럼기준
pd.merge(s1,s2,how='right',on='국적코드')

"""# 5.7 판다스 데이터 그룹핑하기"""

# 국적코드별 입국객수 출력하기
s1=pd.read_excel(filename)
s1.groupby('국적코드').sum()

filename='/content/drive/MyDrive/nation.xlsx'
s1=pd.read_excel(filename)
s1.groupby(['국적코드','성별']).sum()