# -*- coding: utf-8 -*-
"""예제07-1,07-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10AfqT7m4B2GKOiseoRE5Klhce8x2uuoG

# 7장 시각화 라이브러리

## 7.1 데이터 시각화 이해
"""

import matplotlib.pyplot as plt	#1단계
xdata = [2, 3, 4, 5]		    #2단계
ydata = [1, 3, 5, 7]
plt.plot(xdata, ydata)		    #3단계
plt.show()			            #4단계

"""## 7.2 맷플롯립(Matplotlib) 라이브러리"""

import matplotlib.pyplot as plt
plt.title('Line Graph')
xdata = [2, 3, 4, 5]
ydata = [1, 3, 5, 7]
plt.plot(xdata, ydata)
plt.show()

import matplotlib.pyplot as plt
plt.title('Legend')
data1 = [2, 3, 4, 5]
data2 = [8, 6, 4, 2]
plt.plot(data1, label='asc')
plt.plot(data2, label='desc')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
xdata = [2, 3, 4, 5]
ydata = [1, 3, 5, 7]
plt.plot(xdata, ydata, color='red')
plt.show()

import matplotlib.pyplot as plt
xdata = [2, 3, 4, 5]
ydata = [1, 3, 5, 7]
plt.plot(xdata, ydata)
plt.xlabel('X value')
plt.ylabel('Y value')
plt.show()

import matplotlib.pyplot as plt
data1 = [2, 3, 4, 5]
data2 = [8, 6, 4, 2]
plt.plot(data1, color='r', label='dashed', linestyle='--')
plt.plot(data2, color='g', label='dotted', linestyle=':')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
plt.title('X, Y range')
xdata = [5, 10, 15, 20]
ydata = [1, 3, 5, 7]
plt.plot(xdata, ydata, color='b', linestyle='--', marker='o', markersize='10')
plt.xlim(0,25)
plt.ylim(-2,10)
plt.show()

import pandas as pd
my_score = [[50, 90, 95], [60, 75, 100], [75, 85, 90], [85, 75, 90], [95, 80, 85], [90, 85, 80], [95, 80, 75]]
subject = ['kor', 'math', 'eng']
df = pd.DataFrame(my_score, columns=subject)
df.plot(kind='line')

df.plot(kind='area')

df.plot(kind='box')

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel('fine_dust.xlsx', index_col='area')
data2018 = data[2018]

plt.figure(figsize=(15,4))
plt.plot(data2018, color='b', marker='o')
plt.xlabel('area')
plt.ylabel('micrometer')
plt.title('2018 Fine Dust Line Graph')
plt.grid()
plt.show()

plt.figure(figsize=(15,4))

for year in range(2016, 2020):
  chartdata = data[year]
  plt.plot(chartdata, marker='s', label=year)

plt.xlabel('area')
plt.ylabel('micrometer')
plt.title('2016~2019 Fine Dust Line Graph')
plt.legend()
plt.grid()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel('fine_dust.xlsx', index_col='area')
data2017 = data[2017]

plt.figure(figsize=(15,4))
plt.bar(data2017.index, data2017, color='g')
plt.ylim(35,55)
plt.xlabel('area')
plt.ylabel('micrometer')
plt.title('2017 Fine Dust Bar Graph')
plt.grid()
plt.show()

import numpy as np
index = np.arange(4)

plt.figure(figsize=(15,4))

data4 = data.loc['Gyeonggi':'Daegu', 2016:2019]
for year in range(2016, 2020):
  chartdata = data4[year]
  plt.bar(index, chartdata, width=0.2, label=year)
  index = index + 0.2

plt.ylim(35,55)
plt.xlabel('area')
plt.ylabel('micrometer')
plt.xticks(index-0.5, ['Gyeonggi', 'Incheon', 'Busan', 'Daegu'])
plt.title('2016~2019 Fine Dust Group Bar Graph')
plt.legend()
plt.show()

plt.figure(figsize=(10,4))
index = np.arange(4)

data4 = data.loc['Gyeonggi':'Daegu', 2016:2019]
for year in range(2016, 2020):
  chartdata = data4[year]
  plt.barh(index, chartdata, label=year)

plt.xlim(30,55)
plt.ylabel('area')
plt.xlabel('micrometer')
plt.yticks(index, ['Gyeonggi', 'Incheon', 'Busan', 'Daegu'])
plt.title('2016~2019 Fine Dust Group Barh Graph')
plt.legend()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_excel('health_screenings_2020_1000ea.xlsx')

heightdata = data['height']
weightdata = data['weight']

plt.figure(figsize=(10,4))
plt.scatter(heightdata, weightdata)

plt.xlabel('height')
plt.ylabel('weight')
plt.title('2020 Health Screenings Scatter Graph')
plt.grid()
plt.show()

systolic_data = data['systolic']
diastolic_data = data['diastolic']
blood_sugar_data = data['blood_sugar']

plt.figure(figsize=(10,6))

plt.scatter(systolic_data, diastolic_data, color='r', edgecolor='w', label='systolic*diastolic')
plt.scatter(systolic_data, blood_sugar_data, color='g', edgecolor='w', label='systolic*blood_sugar')
plt.scatter(diastolic_data, blood_sugar_data, color='b', edgecolor='w', label='diastolic*blood_sugar')

plt.xlim(40,180)
plt.ylim(30,300)
plt.title('2020 Health Screenings Group Scatter Graph')
plt.legend()
plt.grid()
plt.show()

female_data = data.loc[data.gender==2,['gender','height']]

plt.figure(figsize=(10,6))
plt.hist(female_data['height'], bins=7, label='Female')

plt.xlim(130,180)
plt.xlabel('height')
plt.ylabel('frequency')
plt.title('2020 Health Screenings Female Height Histogram')
plt.legend()
plt.grid()
plt.show()

male_data = data.loc[data.gender==1,['gender','height']]
female_data = data.loc[data.gender==2,['gender','height']]

plt.figure(figsize=(10,6))
plt.hist(male_data['height'], bins=7, alpha=0.5, label='Male')
plt.hist(female_data['height'], bins=7, alpha=0.5, label='Female')

plt.xlim(130,195)
plt.xlabel('height')
plt.ylabel('frequency')
plt.title('2020 Health Screenings Male & Female Height Group Histogram')
plt.legend()
plt.grid()
plt.show()

import numpy as np
height = np.array([male_data['height'], female_data['height']], dtype=object)

plt.figure(figsize=(10,6))
plt.hist(height, bins=6, label=['Male','Female'], stacked=True)

plt.xlim(130,195)
plt.xlabel('height')
plt.ylabel('frequency')
plt.title('2020 Health Screenings Male & Female Height Stacked Histogram')
plt.legend()
plt.show()

import numpy as np
height = np.array([male_data['height'], female_data['height']], dtype=object)

plt.figure(figsize=(8,5))
plt.boxplot(height, labels=['Male','Female'])

plt.ylim(130,200)
plt.xlabel('gender')
plt.ylabel('height')
plt.title('2020 Health Screenings Male & Female Height Box Plot')
plt.show()

plt.figure(figsize=(8,5))
plt.boxplot(height, labels=['Male','Female'], vert=False)

plt.xlim(130,200)
plt.ylabel('gender')
plt.xlabel('height')
plt.title('2020 Health Screenings Male & Female Height Box Plot')
plt.show()

